In [12]:
import pandas as pd
import numpy as np

In [14]:
tmp = pd.read_csv("C:/Bigcontest/bc_data/train_activity.csv")

In [15]:
tmp.head()

,day,acc_id,char_id,server,playtime,npc_kill,solo_exp,party_exp,quest_exp,boss_monster,death,revive,exp_recovery,fishing,private_shop,game_money_change,enchant_count
0,1,75001,397380,aa,1.459994,0.000000,0.000000,0.000000,0.000000,0,0.00000,0.000000,0.0,0.0,1.119053,0.033934,0.0
1,1,75001,216231,aa,0.286785,2.244221,0.046989,0.000000,0.000000,0,0.00000,0.000000,0.0,0.0,0.000000,-0.013933,0.0
2,1,75711,308769,aa,1.049964,2.951697,0.321164,0.166247,0.003463,1,0.24537,0.246819,0.0,0.0,0.000000,-0.001983,0.0
3,1,72230,387177,aa,0.232272,4.035346,0.098944,0.000000,0.001732,0,0.00000,0.000000,0.0,0.0,0.000000,-0.028823,0.0
4,1,34253,339862,aa,1.102106,0.595805,0.003371,0.000000,0.000000,0,0.00000,0.000000,0.0,0.0,0.000000,0.011752,0.0

In [16]:
tmp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1594673 entries, 0 to 1594672
Data columns (total 17 columns):
day                  1594673 non-null int64
acc_id               1594673 non-null int64
char_id              1594673 non-null int64
server               1594673 non-null object
playtime             1594673 non-null float64
npc_kill             1594673 non-null float64
solo_exp             1594673 non-null float64
party_exp            1594673 non-null float64
quest_exp            1594673 non-null float64
boss_monster         1594673 non-null int64
death                1594673 non-null float64
revive               1594673 non-null float64
exp_recovery         1594673 non-null float64
fishing              1594673 non-null float64
private_shop         1594673 non-null float64
game_money_change    1594673 non-null float64
enchant_count        1594673 non-null float64
dtypes: float64(12), int64(4), object(1)
memory usage: 206.8+ MB

In [17]:
tmp.describe()

,day,acc_id,char_id,playtime,npc_kill,solo_exp,party_exp,quest_exp,boss_monster,death,revive,exp_recovery,fishing,private_shop,game_money_change,enchant_count
count,1.594673e+06,1.594673e+06,1.594673e+06,1.594673e+06,1.594673e+06,1.594673e+06,1.594673e+06,1.594673e+06,1.594673e+06,1.594673e+06,1.594673e+06,1.594673e+06,1.594673e+06,1.594673e+06,1.594673e+06,1.594673e+06
mean,1.474104e+01,6.543145e+04,1.985423e+05,1.061710e+00,4.961376e-01,2.339671e-01,1.294045e-01,1.059141e-01,1.239383e-01,7.423919e-02,6.643866e-02,5.700723e-02,1.561828e-01,2.661207e-01,-1.304998e-03,1.625543e-02
std,8.132663e+00,3.749806e+04,1.146751e+05,1.221404e+00,1.120659e+00,1.236939e+00,1.102442e+00,1.092475e+00,3.295112e-01,7.262480e-01,7.246670e-01,1.005531e+00,4.707315e-01,8.297414e-01,8.828235e-01,8.781793e-01
min,1.000000e+00,2.000000e+00,2.000000e+00,2.370121e-03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-8.460951e+01,0.000000e+00
25%,8.000000e+00,3.303900e+04,9.899500e+04,4.503230e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.364748e-03,0.000000e+00
50%,1.500000e+01,6.556400e+04,1.982820e+05,4.645437e-01,4.385879e-03,2.980231e-04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,2.200000e+01,9.766600e+04,2.978440e+05,1.798922e+00,3.495208e-01,2.200882e-02,0.000000e+00,8.658479e-04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.059622e-03,0.000000e+00
max,2.800000e+01,1.304730e+05,3.974430e+05,3.412974e+00,1.783636e+01,6.918458e+01,1.062257e+02,3.595462e+01,1.000000e+00,2.210782e+02,2.223842e+02,7.957624e+01,3.412974e+00,3.412974e+00,7.370887e+01,1.884482e+02